# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Airbnb' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ReactiveCocoa'
  pod 'ObjectMapper'
  pod 'Alamofire'
  pod 'AutoCycleAdview', '~> 1.0.2'

end
