# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Maplocation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'AMapLocation'  #定位 SDK 有IDFA
  # pod 'AMapLocation-NO-IDFA' #无IDFA版定位 SDK See: http://lbs.amap.com/api/ios-location-sdk/guide/crest-project/idfa-guide/
  pod 'AMap3DMap'     #http://lbs.amap.com/api/ios-sdk/guide/create-project/cocoapods/
  pod 'AMapNavi'  #导航SDK

end
